version: "3.9"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./output:/app/output
      - .:/app  # Optional: if your FastAPI app reloads on file changes

#  load-prices:
#    build:
#      context: .
#    command: python assessment_app/utils/load_prices.py
#    volumes:
#      - .:/app
#      - ./assessment_app/data:/app/data
#    environment:
#      - PYTHONPATH=/app
#    depends_on:
#      db:
#        condition: service_healthy
